### ISSUE TITLE
Missing words in the french dictionary

### ISSUE THREAD

**Issue by livan75** [ContentSquare/readapt#141]
Hi, 
I would like to add missing words to the french dictionary (médiathèque for example). I understand that this can be done by updating the frUpdate.csv file. But what I don't know is how to propose a change (sorry I'm a bit of a beginner...)

Thanks for the great work !

**Comment by aradjdi** [comment]
Hello @livan75 
Thanks for contributing!
Exactly, you need to update `frUpdate.csv` and then you need to regenerate the dictionary with this script : `yarn generate-fr-dict`, this will update the `fr.json` dictionnary 
So in #142, we should see two changes, one for `frUpdate.csv` and one for `fr.json`
